name: library-service
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
    networks:
      - customNetwork
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${POSTGRES_URL}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /usr/src/app/node_modules
      - ./src:/usr/src/app/src
  postgres:
    container_name: postgres
    build:
      context: ./src/prisma
      dockerfile: Dockerfile
    networks:
      - customNetwork
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d home_library']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
networks:
  customNetwork:
    driver: bridge
